version: '3.9'

services:
  node:
    container_name: crypto-market-node
    restart: always
    build:
      context: ./server
      dockerfile: ./Dockerfile
    volumes:
      - ./server:/usr/src/app
      - /usr/src/app/node_modules
    env_file:
      - .env
    command: yarn start:dev
    ports:
      - 3001:3001
    networks:
      - app-network

  cripto-market-front:
    container_name: crypto-market-front
    image: node
    restart: always
    build:
      context: ./client
      dockerfile: ./Dockerfile
    volumes:
      - ./client:/usr/src/app
      - /usr/src/app/node_modules
    command: yarn dev
    ports:
      - 3000:3000
    networks:
      - app-network

  mongo:
    container_name: crypto-market-db
    restart: always
    image: mongo
    ports:
      - 27017:27017
    networks:
      - app-network

volumes:
  node:

networks:
  app-network:
    driver: bridge
